---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: ghcr.io/dstoffel/capi-argocd-sync-bundle:0.0.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 0.0.1
          url: ghcr.io/dstoffel/capi-argocd-sync-bundle:0.0.1
  image: ghcr.io/dstoffel/capi-argocd-sync-bundle@sha256:26420a15d2925fd735abaaf5ffbfc82eb3f0f7fe85142e0b3301be44ddb92838
kind: ImagesLock
